### ISSUE TITLE
Producer use arguments doesn't allow for macro expansion

### ISSUE THREAD

**Issue by dennycahan** [qworks-io/rabbitex#14]
I'm trying to do the following but can't:

defmodule Tmp2.QConfig do

  def configuration do

    %{
      Tmp2.Foo.Queue1  => [exchange: "example_queue", worker_count: 3],
      Tmp2.Foo.Queue2  => [exchange: "other_queue", worker_count: 2]
    }

  end
end

defmodule Tmp2.Foo do

  for {module, options} <- Tmp2.QConfig.configuration() do

    defmodule module do

        use RabbitMQ.Producer, options

        @impl true
        def handle_publisher_nack(unackd_messages) do
          Logger.error("Failed to publish messages: #{inspect(unackd_messages)}")
        end

    end
  end
end

This fixes the problem (producer.ex):

Change from:

      @confirm_type unquote(Keyword.get(opts, :confirm_type, :async))
      @exchange unquote(Keyword.fetch!(opts, :exchange))
      @worker_count unquote(Keyword.get(opts, :worker_count, 3))
To:
      @confirm_type Keyword.get(unquote(opts), :confirm_type, :async)
      @exchange Keyword.fetch!(unquote(opts), :exchange)
      @worker_count Keyword.get(unquote(opts), :worker_count, 3)

Many thanks to Kip from the ex_cldr team for figuring it out.

**Comment by slavovojacek** [comment]
@dennycahan hey, thanks for raising this, great to see a valid use case :) 

Please see #15 for a fix.

**Comment by slavovojacek** [comment]
[`0.0.16` released](https://github.com/hqoss/rabbit_mq/runs/652282783?check_suite_focus=true), let me know if all good now.

Best,
Slavo

**Comment by dennycahan** [comment]
Yes, thank you. I'm still having a problem though, I can't figure out how to call your client side publish function within the macro generated modules, but i'm sure that's because this is my first elixir project.

BTW, your library is great. First one I found that properly handles when rabbitmq goes down. I appreciate it.

**Comment by slavovojacek** [comment]
Thanks @dennycahan, glad you like it!

Actually, `publish/3` is **private**. You will need to do something like this:

```elixir
defmodule MyProducer do
  use RabbitMQ.Producer, exchange: "my_exchange"

  def publish_some_update(payload) when is_binary(payload) do
    opts = []
    # You can only call publish within this module, as it's private.
    publish(payload, "routing_key", opts)
  end
end
```

This is by design, as it helps design SDK-like Producers.

**Comment by slavovojacek** [comment]
If all your producers are to publish messages in a similar fashion, you could do something as simple as:

```elixir
defmodule EventProducer do
  use RabbitMQ.Producer, exchange: "events"

  # publish_event/1 is public
  def publish_event(%Event{} = event) do
    opts = [
      # Only useful at the application level
      content_type: "application/json"
    ]

    payload = Jason.encode!(event)

    # publish/3 is private
    publish(payload, event.type, opts)
  end
end
```

Please note I might have mis-typed something.. :D
